/**
 * Exports: a Markdown summary (for a Discord message, a PR, a wiki page)
 * and a PNG "share card" (for a stream overlay screenshot or a social
 * post). Both run entirely client-side — nothing is uploaded anywhere.
 */
import type { PbOddsResult } from "../core/montecarlo.js";
import { simulatePbOdds } from "../core/montecarlo.js";
import {
  pbTotal as computePbTotal,
  playtimeSummary,
  possibleTimeSave,
  resetAnalysis,
  sumOfBest,
} from "../core/stats.js";
import { formatSeconds } from "../core/timespan.js";
import type { Run, TimingMethod } from "../core/types.js";
import { formatCount, formatHours, formatPercent } from "./format.js";

export interface ExportParams {
  readonly method: TimingMethod;
  readonly recentWindow: number;
  readonly simulations: number;
  readonly lookaheadAttempts: number;
}

export function buildMarkdownSummary(run: Run, params: ExportParams): string {
  const pb = computePbTotal(run, params.method);
  const sob = sumOfBest(run, params.method);
  const saves = possibleTimeSave(run, params.method)
    .map((save, i) => ({ name: run.segments[i]?.name ?? `Segment ${i + 1}`, save }))
    .filter((s): s is { name: string; save: number } => s.save !== null && s.save > 0)
    .sort((a, b) => b.save - a.save)
    .slice(0, 5);
  const reset = resetAnalysis(run);
  const playtime = playtimeSummary(run);
  const odds: PbOddsResult = simulatePbOdds(run, pb, {
    method: params.method,
    recentWindow: params.recentWindow,
    simulations: params.simulations,
    lookaheadAttempts: params.lookaheadAttempts,
  });

  const worst = [...reset.points].sort((a, b) => b.deaths - a.deaths)[0];

  const lines = [
    `# ${run.gameName} — ${run.categoryName}`,
    "",
    `Generated by [splitscope](https://antonsoo.github.io/splitscope/) · timing method: ${params.method} · ${formatCount(run.attempts.length)} attempts · ${formatHours(playtime.totalPlaytimeSeconds)} played`,
    "",
    "## Headline",
    "",
    `- **PB:** ${formatSeconds(pb)}`,
    `- **Sum of best:** ${formatSeconds(sob.value)}${sob.complete ? "" : " (incomplete — missing a gold on at least one segment)"}`,
    `- **Total possible time save:** ${pb !== null ? formatSeconds(pb - sob.value) : "—"}`,
    `- **Finished attempts:** ${formatCount(reset.finishedAttempts)} / ${formatCount(reset.totalAttempts)} (${formatPercent(reset.totalAttempts ? reset.finishedAttempts / reset.totalAttempts : null)})`,
    worst
      ? `- **Where runs die most:** ${worst.segmentName} (${formatCount(worst.deaths)} resets)`
      : null,
    "",
    "## Biggest time-save opportunities",
    "",
    "| Segment | Possible save |",
    "| --- | ---: |",
    ...saves.map((s) => `| ${s.name} | ${formatSeconds(s.save)} |`),
    "",
    "## PB odds (Monte Carlo)",
    "",
    odds.insufficientData
      ? "_Not enough segment history in the selected window to simulate._"
      : [
          `- **P(next attempt beats PB):** ${formatPercent(odds.pbProbabilityPerAttempt, 2)} (95% CI ${formatPercent(odds.pbProbabilityPerAttemptCi[0], 2)}–${formatPercent(odds.pbProbabilityPerAttemptCi[1], 2)})`,
          `- **P(≥ 1 PB in next ${odds.lookaheadAttempts} attempts):** ${formatPercent(odds.probabilityAtLeastOnePb, 1)}`,
          `- **Expected attempts to next PB:** ${odds.expectedAttemptsUntilPb === null ? "—" : formatCount(Math.round(odds.expectedAttemptsUntilPb))}`,
          `- Based on ${formatCount(odds.simulations)} simulated attempts, resampled from the last ${params.recentWindow} attempts. Assumes independent segments and a stationary recent-form window — see the app for full assumptions.`,
        ].join("\n"),
    "",
  ];

  return lines.filter((l): l is string => l !== null).join("\n");
}

const CARD_W = 1200;
const CARD_H = 630;

/** Renders the share card to a canvas and triggers a PNG download. */
export function exportPngCard(run: Run, params: ExportParams): void {
  const canvas = document.createElement("canvas");
  canvas.width = CARD_W;
  canvas.height = CARD_H;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  const pb = computePbTotal(run, params.method);
  const sob = sumOfBest(run, params.method);
  const odds = simulatePbOdds(run, pb, {
    method: params.method,
    recentWindow: params.recentWindow,
    simulations: params.simulations,
    lookaheadAttempts: params.lookaheadAttempts,
  });

  // Background
  ctx.fillStyle = "#0b0e11";
  ctx.fillRect(0, 0, CARD_W, CARD_H);

  // Signature delta-rule bar
  const gradient = ctx.createLinearGradient(0, 0, CARD_W, 0);
  gradient.addColorStop(0, "#ff5c5c");
  gradient.addColorStop(0.5, "#f5c542");
  gradient.addColorStop(1, "#3ddc84");
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, CARD_W, 6);

  ctx.fillStyle = "#5a6472";
  ctx.font = "600 20px monospace";
  ctx.fillText("SPLITSCOPE", 64, 76);

  ctx.fillStyle = "#8b95a1";
  ctx.font = "500 26px sans-serif";
  ctx.fillText(`${run.gameName} — ${run.categoryName}`, 64, 116);

  ctx.fillStyle = "#5a6472";
  ctx.font = "500 16px monospace";
  ctx.fillText("PERSONAL BEST", 64, 200);
  ctx.fillStyle = "#f5c542";
  ctx.font = "700 96px monospace";
  ctx.fillText(formatSeconds(pb), 60, 280);

  const stats: [string, string][] = [
    ["SUM OF BEST", formatSeconds(sob.value)],
    ["ATTEMPTS", formatCount(run.attempts.length)],
    [
      "P(PB NEXT ATTEMPT)",
      odds.insufficientData ? "—" : formatPercent(odds.pbProbabilityPerAttempt, 2),
    ],
    [
      `P(≥1 PB / ${odds.lookaheadAttempts})`,
      odds.insufficientData ? "—" : formatPercent(odds.probabilityAtLeastOnePb, 1),
    ],
  ];

  const colW = (CARD_W - 128) / stats.length;
  stats.forEach(([label, value], i) => {
    const cx = 64 + i * colW;
    ctx.fillStyle = "#5a6472";
    ctx.font = "600 14px monospace";
    ctx.fillText(label, cx, 400);
    ctx.fillStyle = "#e8ecef";
    ctx.font = "700 34px monospace";
    ctx.fillText(value, cx, 440);
  });

  ctx.strokeStyle = "#262d36";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(64, 470);
  ctx.lineTo(CARD_W - 64, 470);
  ctx.stroke();

  ctx.fillStyle = "#5a6472";
  ctx.font = "500 15px monospace";
  ctx.fillText(`Timing: ${params.method}   ·   generated locally, nothing uploaded`, 64, 520);
  ctx.fillText("antonsoo.github.io/splitscope", 64, 548);

  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `splitscope-${run.gameName.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }, "image/png");
}

export function downloadText(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
